### ISSUE TITLE
Route changed, translation extractor don't notice

### ISSUE THREAD

**Issue by raistlin** [schmittjoh/JMSI18nRoutingBundle#105]
I had this route:

``` yaml
help:
    pattern: /help/{slug}
    defaults: { _controller: AcmeDefaultBundle:Default:help }
```

And exported translations with

``` bash
php app/console translations:extract ...
```

Now I just changed route to:

``` yaml
help:
    pattern: /help
    defaults: { _controller: AcmeDefaultBundle:Default:help }
```

And run again translation exporter to update my translated routes.

But my files at app/Resources/translations/ still show route /help/{slug} but dont show route /help

I had to manually remove /help/{slug} entries from translation files, so translation extract could create correct entries.
