### ISSUE TITLE
Routing problem when a route has two identicals traductions (locale is host based) - Symfony 2.3

### ISSUE THREAD

**Issue by fgravelaine** [schmittjoh/JMSI18nRoutingBundle#106]
Our project has locale based on host : 

``` yml
jms_i18n_routing:
  default_locale: fr
  locales: [en,fr]
  strategy: custom
  redirect_to_host: false
  hosts:
    en: %obtao_host%
    fr: fr.%obtao_host% 
```

We defined a route : 

``` yml
ObtaoBundle_root : 
    pattern : /
    defaults: { _controller: ObtaoBundle:Default:index }
```

Translation is the same for en and fr ("/")

In our project, since symfony 2.3 update, this configuration throws an exception for 'fr.obtao.localhost' (I18nRouter.php l.226) : 

```
No route found for "GET /"
```

After some investigations, the code search for a locale, then check if the locale found correspond to the locale of the configured host. 
In 2.2, the locale at this point was "fr" (as expected)
In 2.3 the locale is "en" (value of $defaultLocale in Symfony HttpFoundation Request)

Indeed, in I18Router.php at line 172 : 

``` php
$currentLocale = $this->context->getParameter('_locale')
```

in 2.2 , after this, $currentLocale was null, 
in 2.3 $currentLocale = 'en'. 

Is there a bug, or is something wrong in my configuration ?

Thanks!
