### ISSUE TITLE
Multiple firewalls: The security context contains no authentication token.

### ISSUE THREAD

**Issue by d00001** [schmittjoh/JMSI18nRoutingBundle#109]
"The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL"

```
   f1:
        pattern: ^/f1
        form_login:
            provider: f1_user
            csrf_provider: form.csrf_provider
            check_path:  f1_user_security_check
            login_path:  f1_main_index
        logout:
            path: f1_security_logout
        anonymous: true

    main:
        pattern: ^/main
        form_login:
            provider: fos_userbundle
            csrf_provider: form.csrf_provider
            check_path:  fos_user_security_check
            login_path:  fos_main_index
        logout:
            path: fos_user_security_logout
        anonymous: true
```

Using {_locale} does not work. One solution is using (en|es|fr). Is there any other way?
