### ISSUE TITLE
Internationalization based on subdomain

### ISSUE THREAD

**Issue by khal3d** [schmittjoh/JMSI18nRoutingBundle#110]
Hello, Sorry for write this question as an issue but I didn't know where to ask questions like this.

I'm working on a project which will support multiple countries separately based on sub-domain (ie: egypt.example.com & morocco.example.com) (Same code, Different content)

What I want is adding locale routing for each sub domain separately 
for example: 
Domain egypt.example.com

```
egypt.example.com/welcome (English)
egypt.example.com/ar/welcome (Arabic)
```

and for domain morocco.example.com

```
morocco.example.com/welcome (French)
morocco.example.com/ar/welcome (Arabic)
```

If this is not possible with the current version of JMSI18nRoutingBundle I hope you guys add it as feature because this bundle is awesome and it supposed to be internationalization (i18n) routing bundle not just localization (i10n) routing bundle

Here is the configuration that I expect and maybe help you to understand the question more

```
jms_i18n_routing:
    egypt:
        default_locale: en
        locales: [ar, en]
        strategy: prefix_except_default
        hosts: [egypt.example.com, example.eg]
    morocco:
        default_locale: fr
        locales: [ar, fr]
        strategy: prefix_except_default
        hosts: [morocco.example.com, example.ma]
```

Thank you so much,  You are really doing a great job :)
