### ISSUE TITLE
Incompatibility with Symfony2.4

### ISSUE THREAD

**Issue by jamarisi** [schmittjoh/JMSI18nRoutingBundle#115]
Hello, yesterday I updated one of my projects to Symfony2.4 and I'm having problems with the i18n since then.
First, my language switcher generates only routes for the current language. It ignores the _locale param and if I'm currently using the es locale, it generates all the links with the same locale.

```
<ul class="pull-right nav navbar-nav">
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            {{ app.request.get('_locale')|upper }}
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            {% for locale in ['es', 'en', 'pt'] %}
            <li>
                <a href="{{ path(app.request.get('_route'), app.request.get('_route_params')|merge({ '_locale': locale })) }}">{{ locale|upper }}</a>
            </li>
            {% endfor %}
        </ul>
    </li>
</ul>
```

It was working perfectly with Symfony2.3.

Second, I'm having problems with the security configuration. In my security.yml I have something like

```
security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:   fos_user_security_logout
```

But now the login_path, check_path and path in logout are no longer recognized. There are no exceptions when the file is parsed, but the listeners are not invoked when the form is submitted. It works when I add the localized paths, like es__RG__fos_user_security_login, but I cannot hard code the localized path for every locale. Like the first problem, it was working fine with Symfony2.3.

The bundle configuration is:

```
jms_i18n_routing:
    default_locale: es
    locales: [es, en, pt]
    strategy: prefix
```

Any ideas that I can try to fix these issues?

Thank you in advance.
