### ISSUE TITLE
Host redirected to english version

### ISSUE THREAD

**Issue by fungio** [schmittjoh/JMSI18nRoutingBundle#128]
Hello

I've got a problem with the JMSI18RoutingBundle. I've the configuration as followed:

```
jms_i18n_routing:
    default_locale: fr
    locales: [fr, en]
    strategy: custom
    hosts:
        en: www.mysite.com
        fr: www.mysite.fr
    redirect_to_host: true
```

If I go to www.mysite.com I have the english version as expected. However, if I go to www.mysite.fr then I'm redirected to the .com and still have the english version.

If I set redirect_to_host to false, then I have : No route found for "GET /".

Am I missing something ? Did anybody have the same issue ?

Thanks
