### ISSUE TITLE
multiple hosts with same locales

### ISSUE THREAD

**Issue by pcampr** [schmittjoh/JMSI18nRoutingBundle#13]
proposal for feature addition:

currently it's possible to have only one host per locale, e.g.

```
jms_i18n_routing:
    default_locale: cs
    locales: [cs, en]
    strategy: custom
    hosts:
        cs: domain.cz
        en: domain.com
```

if I need to have more than 1 domain with same locale, I am unable to do this... following setup doesn't work (end up with exception 'Invalid type for path "jms_i18n_routing.hosts.cs". Expected scalar, but got array.')

```
    hosts:
        cs: [domain.cz, domain2.cz]
```

it would be nice to add such a support for multiple domains with same locale
