### ISSUE TITLE
how to set the routing translation based on annotation?

### ISSUE THREAD

**Issue by mappedinn** [schmittjoh/JMSI18nRoutingBundle#149]
All the routing of my website is realized based on the annotations. Now, I want to translate my routing. To realize that, I tried to use the bundle [JMSI18nRoutingBundle][1].

Nevetheless, the documentation does not give any example how to specify the route for each locale.

This is an action with its routing, how to translate it?

    /**
     * @Route("/welcome", name="welcome")
     * @Template()
     */
    public function indexAction() {
        return array();
    }

Thanks, 

  [1]: https://github.com/schmittjoh/JMSI18nRoutingBundle

**Comment by picks44** [comment]
UP, same problem here

**Comment by stof** [comment]
this bundle does not allow to specify different paths for each locale. It relies on the translator to translate route patterns

**Comment by picks44** [comment]
Yes, but the real point is : how do we get the translation from routing based on annotations ? I tried to extract like the doc says, but I'm not getting anything.

**Comment by feyyazesat** [comment]
Yes it does, for instance I use /profile/dashboard for locale en, and /profil for locale tr  and all my routes are translated based on locales and I'm using annotation routing. Even I do for fos bundle, hwi oauth bundle too.

```bash
php bin/console translation:extract tr --bundle=PetsnjoyFrontendBundle --enable-extractor=jms_i18n_routing --output-format=yml --exclude-dir=cache --exclude-dir=data --exclude-dir=logs --exclude-dir=Tests --exclude-dir=Service --output-dir="app/Resources/translations"
```
This is the console command which I'm using.

and it will create routes.tr.yml file which contains all of your routes.
Example
```yml
# Desc: /profile/calendar/{id}
my_profile_calendar: '/profil/takvim/{id}'

# Desc: /profile/dashboard
my_profile_dashboard: /profil

# Desc: /profile/edit/personal-info
my_profile_edit_personal_info: /profil/duzenle/kisisel-bilgiler

# Desc: /profile/edit/photo
my_profile_edit_photo: /profil/duzenle/fotograf
```
