### ISSUE TITLE
HTTP/HTTPS depends of locale

### ISSUE THREAD

**Issue by AntoineLemaire** [schmittjoh/JMSI18nRoutingBundle#158]
Is there a way to define a locale as https an others as http ?

Like for example:

```
jms_i18n_routing:
    locales:
        - fr_FR
        - en_FR
        - de_DE
        - es_ES
    hosts:
        fr_FR: mywebsite.fr
        en_FR: en.mywebsite.fr
        es_ES: mywebsite.es
        de_DE: mywebsite.de
    secure:
        fr_FR: true
        en_FR: true
        es_ES: false
        de_DE: true
```

To get 

fr_FR => https://mywebsite.fr
en_FR => https://en.mywebsite.fr
de_DE => https://mywebsite.de
es_ES => http://mywebsite.es

Actually, if I generate url with `url('route_name',{'_locale':'es_ES'})` in a Twig of a page of fr_FR, I get https://mywebsite.es instead of http://mywebsite.es
