### ISSUE TITLE
Need a way to ignore some bundles

### ISSUE THREAD

**Issue by ghost** [schmittjoh/JMSI18nRoutingBundle#16]
I have two bundles, one requires i18n the other not. 

``` yaml
CheFrontBundle:
    resource: "@CheFrontBundle/Controller/"
    type:     annotation
    prefix:   /

_CheAdminBundle:
    resource: "@CheAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
```

So i added _ to the CheAdminBundle, but it is still visible to the JMSI18nRoutingBundle bundle. However i added the _ to the route inside the bundle CheAdminBundle:

from: 

``` yaml
@Route("/", name = "index")
```

to

``` yaml
@Route("/", name = "_index")
```

and this route got ignore.

However it would be a hell to prefix all the routes inside this bundle. 
So is there some other way to ignore this bundle,  or mayble make the 

``` yaml
_CheAdminBundle:
    resource: "@CheAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
```

syntax work?
