### ISSUE TITLE
wrong routes.xx.yml conten when I use locale_country (e.g. en_GB)

### ISSUE THREAD

**Issue by hubikz** [schmittjoh/JMSI18nRoutingBundle#19]
configuration:

``` yml
jms_i18n_routing:
    default_locale: en_GB
    locales: [en_EN, en_GB]
    strategy: custom
    hosts:
        en_EN: %host_name.en_EN%
        en_GB: %host_name.en_GB%
```

routing file for en_GB (routes.en_GB.yml) after translation:extract or i18n:extract-routes

``` yml
# Desc: /hello/{name}
GB_xxx_default_index: '/hello/{name}'   # FIXME
# Desc: /hello/{name}
xxx_default_index: '/hello/{name}'   # FIXME
```

Symfony documentation says:
"We recommended the ISO639-1 language code, an underscore (_), then the ISO3166 country code (e.g. fr_FR for French/France)."
(http://symfony.com/doc/2.0/book/translation.html)
