### ISSUE TITLE
Multiple translated path for same route

### ISSUE THREAD

**Issue by CharlyPoppins** [schmittjoh/JMSI18nRoutingBundle#191]
Hi,

I'm trying to do something like this :

```
site_about:
    path: /a-propos
    path: /en/about-us
    defaults: { _controller: SiteBundle:Default:About }

site_food:
    path: /nourriture
    path: /en/food
    defaults: { _controller: SiteBundle:Default:Food }
```

is there a way to do this with this bundle ?
