### ISSUE TITLE
Add locale to a route with slug [symfony2]

### ISSUE THREAD

**Issue by aimeric** [schmittjoh/JMSI18nRoutingBundle#194]
Hi,

I'm trying to translate the page of my website, i used the bundle `JMSI18nRoutingBundle,` but when i'm trying to reach certain pages of the website i have the following error:

> An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "page_slug" as such route does not exist.") in SonataPageBundle:Block:block_container.html.twig at line 15.

I noticed that i have the error with the pages that have a block of content that is stored in the database.

I'm using` SonataPageBundle` and` SonataBlockBundle `to edit certain page of the website.

here Below 2 routes that giving me the error:

```
privacy_policy:
    path: /privacy_policy
    defaults:  {  _controller: FLYBookingsBundle:Default:privacypolicy }


product:
    pattern: /product/{id}
    defaults: { _controller: FLYBookingsBundle:Post:product }
```
`
<li><a href="{{ path('privacy_policy') }}">Privacy Policy</a></li>`

Thank you
