### ISSUE TITLE
translated routes defaulting to Russian when default locale is en

### ISSUE THREAD

**Issue by PaddyLock** [schmittjoh/JMSI18nRoutingBundle#227]
Hi, none of my translated routes appear in the generated url, apart from a couple of them which are using the Russian locale which is not my default. I don't understand what is going on. This happened since I upgraded to Symfony 4. My config is:

```
jms_translation:
    configs:
        app:
            dirs: ["%kernel.root_dir%", "%kernel.root_dir%/../src/"]
            output_dir: "%kernel.root_dir%/../translations/"
            ignored_domains: [FOSUserBundle]
            excluded_names: ["*TestCase.php", "*Test.php", "Alert.php", "Book.php", "Brand.php", "Category.php", "CategoryGroup.php", "Collection.php", "Content.php", "DiscountGroup.php", "Faq.php", "Form.php", "FormDiscount.php", "Latest.php", "Popular.php", "Post.php", "PostageMethod.php", "PostageRate.php", "PostageZone.php", "PostageZoneCountry.php", "Potency.php", "PotencyRange.php", "Product.php", "ProductGroup.php", "Scale.php", "Size.php", "SubCategory.php", "SubTopic.php", "Taxon.php", "Taxonomy.php", "Topic.php", "VatRate.php", "Document.php", "Download.php", "Email.php", "Testimonial.php", "Stock.php"]
            excluded_dirs: [cache, data, logs, Features, Tests, DataFixtures, Form/Admin, Controller/Admin]
            extractors: []
```

```
jms_i18n_routing:
    default_locale: en
    locales: "%languages%"
    strategy: prefix_except_default
```

translations are generated in `translations/routes.cs.xliff` etc

routing is in annotations.yaml

```
controllers:
    resource: ../../src/Controller/
    type: annotation
    options: { i18n: true }
```

actions have `options={"utf8": true}`
