### ISSUE TITLE
Route annotation cache

### ISSUE THREAD

**Issue by pohlaniacz** [schmittjoh/JMSI18nRoutingBundle#235]
Hi, when using route annotation, ie:
```
use Symfony\Component\Routing\Annotation\Route;
/**
* @Route("/{id}/edit", name="record_edit")
*/
```
and then change (url only, without name) to:
```
/**
* @Route("/{id}/new_edit", name="record_edit")
*/
```
new route is not available, still old one is in use.. 
Config for this bundle:
```
jms_i18n_routing:
    default_locale: "%locale%"
    locales: [en, de]
    strategy: prefix_except_default
```

And also have jms_translation with jms_i18n_routing as extractor
```
jms_translation:
    configs:
        web:
            dirs: [ "%kernel.project_dir%/src/Acme/DemoBundle" ]
            output_dir: "%kernel.project_dir%/app/Resources/translations/web"
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]
            output-format: xliff
            extractors: [jms_i18n_routing]
```

Tried
```
php bin/console bazinga:js-translation:dump web/js
php bin/console fos:js-routing:dump --locale=en --target="web/js/fos_js_routes_en.js"
```
with no result. Also tried to delete some dirs in cache and clear the cache but with no result. Don't know if doing something wrong or there is an issue with config. Only option now is to change route name.
