### ISSUE TITLE
Possibility and/or best way to use this bundle with annotations

### ISSUE THREAD

**Issue by Ph3nol** [schmittjoh/JMSI18nRoutingBundle#41]
Hi,

First, thank you for this very useful bundle!

I'm trying to use it with annotations into controllers without entire success... Have you an example about this utilization?

Here is my config parameters:

``` yml
jms_i18n_routing:
    default_locale: en
    locales: [en, fr]
    strategy: prefix_except_default
```

What I'd want is 2 distinct URLs like these for example:
- /welcome
- /fr/bienvenue

Thank you for your help!
