### ISSUE TITLE
wrong url generated using twig path function in Symfony 2.1 (master)

### ISSUE THREAD

**Issue by toooni** [schmittjoh/JMSI18nRoutingBundle#54]
the symfony/twig path function does not generate the correct url in symfony 2.1:
when i do have set a locale like fr_CH my links are like: `mylink.ch/xyz` instead of `mylink.ch/fr/xyz`.. for example in sf 2.0 this was working as expected.

I do have the following settings:

```
jms_i18n_routing:
    default_locale: de
    locales: [de, fr, en, it]
    strategy: prefix_except_default
```
