### ISSUE TITLE
Translate catch-all routes with prefix_except_default

### ISSUE THREAD

**Issue by tiagojsag** [schmittjoh/JMSI18nRoutingBundle#83]
Hi,

I'm using this bundle with a catch-all route and a prefix_except_default config. My routing config is the following:

```
generic_route:
    pattern: /{url}/
    defaults: { _controller: SomeThingBundle:Switch:index, url: null, _locale: es }
    requirements:
        _locale: es|uk|us|pt|it|de|mx
        url: ".+"
        _scheme:  http
```

Problem is that this only works for default 'es' locale. In all other cases, the locale falls back to 'es' and the, let's say, 'uk' locale is passed to the controller as part of the 'url' variable.
Is there any way I can configure the bundle to work in this scenario?
cheers
