### ISSUE TITLE
Generate path add unnecessary query string

### ISSUE THREAD

**Issue by kuboslav** [schmittjoh/JMSI18nRoutingBundle#88]
I have following configuration:

```
jms_i18n_routing:
    default_locale: cs
    locales: [cs, en]
    strategy: custom
    hosts:
        cs: domain.cs
        en: domain.en
    redirect_to_host: true
```

When I want to generate url by `{{ path("homepage", {"_locale": "en"}) }}`, it add `?_locale=en` to URL.
