### ISSUE TITLE
Strategy "custom" don't work ?

### ISSUE THREAD

**Issue by JulienBreux** [schmittjoh/JMSI18nRoutingBundle#9]
In app/config/config_dev.yml

``` yml
jms_i18n_routing:
    default_locale: fr
    locales: [fr, en]
    strategy: custom
    hosts:
        fr: fr.domain.local
        en: en.domain.local
```

In app/Resources/translations/routes.en.yml

``` yml
MyLittleBundle_homepage: '/hello/{name}'
```

In app/Resources/translations/routes.fr.yml

``` yml
MyLittleBundle_homepage: '/bonjour/{name}'
```

**OK (anormal)** http://fr.domain.local/hello/Name
**OK** http://en.domain.local/hello/Name

**FAILLED** http://fr.domain.local/bonjour/Name
**FAILLED (normal)** http://fr.domain.local/bonjour/Name

Did I miss something?
